


local mm6MapProgression={
--MM6
  ["New Sorpigal"] = 1,
  ["Goblinwatch"] = 4,
  ["The Abandoned Temple"] = 5,
  ["Castle Ironfist"] = 6,
  ["Shadow Guild Hideout"] = 7,
  ["Misty Islands"] = 8,
  ["Bootleg Bay"] = 9,
  ["Temple of the Fist"] = 10,
  ["Temple of Tsantsa"] = 11,
  ["Silver Helm Outpost"] = 12,
  ["Hall of the Fire Lord"] = 13,
  ["Free Haven"] = 14,
  ["Free Haven Sewer"] = 15,
  ["Temple of Baa"] = 16,
  ["Dragoons' Caverns"] = 17,
  ["Frozen Highlands"] = 18,
  ["Shadow Guild"] = 19,
  ["Icewind Keep"] = 20,
  ["Dragoons' Keep"] = 21,
  ["Corlagon's Estate"] = 22,
  ["Tomb of Ethric the Mad"] = 23,
  ["Temple of the Moon"] = 24,
  ["Mire of the Damned"] = 25,
  ["Temple of the Sun"] = 26,
  ["Snergle's Caverns"] = 27,
  ["Snergle's Iron Mines"] = 28,
  ["Silver Cove"] = 29,
  ["The Monolith"] = 30,
  ["Silver Helm Stronghold"] = 31,
  ["Warlord's Fortress"] = 32,
  ["Dragon's Lair"] = 33,
  ["Blackshire"] = 34,
  ["Lair of the Wolf"] = 35,
  ["Gharik's Forge"] = 36,
  ["Eel Infested Waters"] = 37,
  ["Agar's Laboratory"] = 38,
  ["Castle Alamos"] = 39,
  ["Kriegspire"] = 40,
  ["Devil Outpost"] = 41,
  ["Superior Temple of Baa"] = 42,
  ["Castle Darkmoor"] = 43,
  ["Temple of the Snake"] = 44,
  ["Paradise Valley"] = 45,
  ["Castle Kriegspire"] = 46,
  ["Caves of the Dragon Riders"] = 47,
  ["Hermit's Isle"] = 48,
  ["Supreme Temple of Baa"] = 49,
  ["Dragonsand"] = 50,
  ["Tomb of VARN"] = 51,
  ["Sweet Water"] = 52,
  ["Control Center"] = 53,
  ["The Hive"] = 54,
}

local mm7MapProgression={
  ["Emerald Island"] = 1,
  ["The Dragon's Lair"] = 1,
  ["The Temple of the Moon"] = 1,
  ["Castle Harmondale"] = 4,
  ["Harmondale"] = 5,
  ["White Cliff Cave"] = 6,
  ["The Tularean Forest"] = 7,
  ["The Hall under the Hill"] = 8,
  ["Erathia"] = 9,
  ["The Bandit Caves"] = 10,
  ["The Erathian Sewers"] = 11,
  ["The Barrow Downs"] = 12,
  ["Barrow I"] = 13,
  ["Barrow II"] = 13,
  ["Barrow III"] = 13,
  ["Barrow IV"] = 13,
  ["Barrow V"] = 13,
  ["Barrow VI"] = 13,
  ["Barrow VII"] = 13,
  ["Barrow VIII"] = 13,
  ["Barrow IX"] = 13,
  ["Barrow X"] = 13,
  ["Barrow XI"] = 13,
  ["Barrow XII"] = 13,
  ["Barrow XIII"] = 13,
  ["Barrow XIV"] = 13,
  ["Barrow XV"] = 13,
  ["Zokarr's Tomb"] = 13,
  ["The Haunted Mansion"] = 14,
  ["Stone City"] = 15,
  ["Deyja"] = 16,
  ["The Tidewater Caverns"] = 18,
  ["Evenmorn Island"] = 19,
  ["The Bracada Desert"] = 20,
  ["The Red Dwarf Mines"] = 21,
  ["Tatalia"] = 22,
  ["Grand Temple of the Sun"] = 23,
  ["Grand Temple of the Moon"] = 24,
  ["Avlee"] = 25,
  ["The Tularean Caves"] = 26,
  ["Fort Riverstride"] = 26,
  ["Nighon Tunnels"] = 27,
  ["Lord Markham's Manor"] = 28,
  ["Wromthrax's Cave"] = 29,
  ["The Hall of the Pit"] = 30,
  ["The Breeding Zone"] = 31,
  ["The Walls of Mist"] = 31,
  ["Castle Navan"] = 32,
  ["The Temple of Baa"] = 33,
  ["The School of Sorcery"] = 33,
  ["The Hidden Tomb"] = 34,
  ["Castle Gryphonheart"] = 35,
  ["William Setag's Tower"] = 35,
  ["The Mercenary Guild"] = 36,
  ["Watchtower 6"] = 37,
  ["Celeste"] = 38,
  ["The Pit"] = 38,
  ["Temple of the Light"] = 39,
  ["Temple of the Dark"] = 39,
  ["Castle Lambent"] = 40,
  ["Castle Gloaming"] = 40,
  ["The Wine Cellar"] = 41,
  ["Clanker's Laboratory"] = 41,
  ["Thunderfist Mountain"] = 42,
  ["Mount Nighon"] = 43,
  ["The Maze"] = 44,
  ["The Small House"] = 45,
  ["Tunnels to Eeofol"] = 46,
  ["The Titans' Stronghold"] = 47,
  ["The Land of the Giants"] = 48,
  ["The Dragon Caves"] = 49,
  ["Colony Zod"] = 50,
  ["Shoals"] = 51,
  ["The Lincoln"] = 52,
}

local mm8MapProgression={
  --MM8
  ["Dagger Wound Island"] = 1,
  ["Abandoned Temple"] = 4,
  ["Ravenshore"] = 5,
  ["Dire Wolf Den"] = 6,
  ["Smuggler's Cove"] = 7,
  ["Chapel of Eep"] = 8,
  ["Alvar"] = 9,
  ["Wasp Nest"] = 10,
  ["Ogre Fortress"] = 11,
  ["Ironsand Desert"] = 12,
  ["Troll Tomb"] = 13,
  ["Dark Dwarf Compound"] = 14,
  ["Church of Eep"] = 15,
  ["Ravage Roaming"] = 16,
  ["Barbarian Fortress"] = 17,
  ["Grand Temple of Eep"] = 18,
  ["Balthazar Lair"] = 19,
  ["Murmurwoods"] = 20,
  ["Ancient Troll Home"] = 21,
  ["Shadowspire"] = 22,
  ["Mad Necromancer's Lab "] = 23,
  ["Temple of the Sun"] = 24,
  ["Uplifted Library"] = 25,
  ["Chain of Fire"] = 26,
  ["The Crypt of Korbu"] = 27,
  ["Cyclops Larder"] = 28,
  ["Garrote Gorge"] = 29,
  ["Naga Vault"] = 30,
  ["Dragon Hunter's Camp"] = 31,
  ["Vampire Crypt"] = 32,
  ["Necromancers' Guild"] = 33,
  ["Pirate Outpost"] = 34,
  ["Small Sub Pen"] = 35,
  ["Regna"] = 36,
  ["Pirate Stronghold"] = 37,
  ["Passage Under Regna"] = 38,
  ["Abandoned Pirate Keep"] = 39,
  ["Druid Circle"] = 40,
  ["Plane of Air"] = 41,
  ["Castle of Air"] = 42,
  ["Plane of Water"] = 43,
  ["Plane of Fire"] = 44,
  ["War Camp"] = 45,
  ["Castle of Fire"] = 46,
  ["Plane of Earth"] = 47,
  ["Dragon Cave"] = 48,
  ["Ilsingore's Cave"] = 49,
  ["Old Loeb's Cave"] = 50,
  ["Yaardrake's Cave"] = 51,
  ["Escaton's Crystal"] = 52,
  ["Plane Between Planes"] = 53,
  ["Escaton's Palace"] = 54,
  ["Prison of the Lord of Air"] = 55,
  ["Prison of the Lord of Earth"] = 56,
  ["Prison of the Lord of Water"] = 57,
  ["Prison of the Lord of Fire"] = 58,
}
function events.GameInitialized2()
    --set doom/insanity map levels to work like Madness,


--vars.UseDoomMapLevels=true

--debug.Message("Setting up Doom Map Levels %s", vars.UseDoomMapLevels)
	doomMapLevels={}
	for key, value in pairs(mm6MapProgression) do
		doomMapLevels[key]=round(((value/54)*100)^1.5)
	end

	for key, value in pairs(mm7MapProgression) do
		doomMapLevels[key]=round(((value/52)*100)^1.5)
	end

	for key, value in pairs(mm8MapProgression) do
		doomMapLevels[key]=round(((value/58)*100)^1.5)
	end

	doomMapLevels["Basement of the Breach"] = 1000
	doomMapLevels["The Breach"] = 1000
	doomMapLevels["The Arena"] = 1
	doomMapLevels["Pending"] = 1
	doomMapLevels["NWC"] = 1

end